name: Crystal CI

on:startup
  push:Shards
    branches: [ master ]
  pull_request: Create main.yml
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
