name: Crystal CI

on:startup
  push:create main.yml
    branches: [ master ]
  pull_request: Crystal.create.yml
    branches: [ master ]

jobs:Shards
  build: main

    runs-on: ubuntu-latest

    container: CI
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
